/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  IsOptional,
  MaxLength,
  IsBoolean,
  IsDate,
  ValidateNested,
  IsEnum,
} from "class-validator";
import { Type } from "class-transformer";
import { ParentProfileCreateNestedManyWithoutUsersInput } from "./ParentProfileCreateNestedManyWithoutUsersInput";
import { EnumUserRole } from "./EnumUserRole";
import { IsJSONValue } from "../../validators";
import { GraphQLJSON } from "graphql-type-json";
import { InputJsonValue } from "../../types";
import { SchoolWhereUniqueInput } from "../../school/base/SchoolWhereUniqueInput";
import { StudentProfileCreateNestedManyWithoutUsersInput } from "./StudentProfileCreateNestedManyWithoutUsersInput";
import { TeacherProfileCreateNestedManyWithoutUsersInput } from "./TeacherProfileCreateNestedManyWithoutUsersInput";

@InputType()
class UserCreateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  email?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  firstName?: string | null;

  @ApiProperty({
    required: false,
    type: Boolean,
  })
  @IsBoolean()
  @IsOptional()
  @Field(() => Boolean, {
    nullable: true,
  })
  isActive?: boolean | null;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  lastLogin?: Date | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  lastName?: string | null;

  @ApiProperty({
    required: false,
    type: () => ParentProfileCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => ParentProfileCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => ParentProfileCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  parentProfiles?: ParentProfileCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  password!: string;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  passwordHash?: string | null;

  @ApiProperty({
    required: false,
    enum: EnumUserRole,
  })
  @IsEnum(EnumUserRole)
  @IsOptional()
  @Field(() => EnumUserRole, {
    nullable: true,
  })
  role?: "Option1" | null;

  @ApiProperty({
    required: true,
  })
  @IsJSONValue()
  @Field(() => GraphQLJSON)
  roles!: InputJsonValue;

  @ApiProperty({
    required: false,
    type: () => SchoolWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => SchoolWhereUniqueInput)
  @IsOptional()
  @Field(() => SchoolWhereUniqueInput, {
    nullable: true,
  })
  school?: SchoolWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => StudentProfileCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => StudentProfileCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => StudentProfileCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  studentProfiles?: StudentProfileCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: () => TeacherProfileCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => TeacherProfileCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => TeacherProfileCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  teacherProfiles?: TeacherProfileCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  username!: string;
}

export { UserCreateInput as UserCreateInput };
