/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { UserService } from "../user.service";
import { UserCreateInput } from "./UserCreateInput";
import { User } from "./User";
import { UserFindManyArgs } from "./UserFindManyArgs";
import { UserWhereUniqueInput } from "./UserWhereUniqueInput";
import { UserUpdateInput } from "./UserUpdateInput";
import { ParentProfileFindManyArgs } from "../../parentProfile/base/ParentProfileFindManyArgs";
import { ParentProfile } from "../../parentProfile/base/ParentProfile";
import { ParentProfileWhereUniqueInput } from "../../parentProfile/base/ParentProfileWhereUniqueInput";
import { StudentProfileFindManyArgs } from "../../studentProfile/base/StudentProfileFindManyArgs";
import { StudentProfile } from "../../studentProfile/base/StudentProfile";
import { StudentProfileWhereUniqueInput } from "../../studentProfile/base/StudentProfileWhereUniqueInput";
import { TeacherProfileFindManyArgs } from "../../teacherProfile/base/TeacherProfileFindManyArgs";
import { TeacherProfile } from "../../teacherProfile/base/TeacherProfile";
import { TeacherProfileWhereUniqueInput } from "../../teacherProfile/base/TeacherProfileWhereUniqueInput";

export class UserControllerBase {
  constructor(protected readonly service: UserService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: User })
  async createUser(@common.Body() data: UserCreateInput): Promise<User> {
    return await this.service.createUser({
      data: {
        ...data,

        school: data.school
          ? {
              connect: data.school,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        email: true,
        firstName: true,
        id: true,
        isActive: true,
        lastLogin: true,
        lastName: true,
        passwordHash: true,
        role: true,
        roles: true,

        school: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
        username: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [User] })
  @ApiNestedQuery(UserFindManyArgs)
  async users(@common.Req() request: Request): Promise<User[]> {
    const args = plainToClass(UserFindManyArgs, request.query);
    return this.service.users({
      ...args,
      select: {
        createdAt: true,
        email: true,
        firstName: true,
        id: true,
        isActive: true,
        lastLogin: true,
        lastName: true,
        passwordHash: true,
        role: true,
        roles: true,

        school: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
        username: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: User })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async user(
    @common.Param() params: UserWhereUniqueInput
  ): Promise<User | null> {
    const result = await this.service.user({
      where: params,
      select: {
        createdAt: true,
        email: true,
        firstName: true,
        id: true,
        isActive: true,
        lastLogin: true,
        lastName: true,
        passwordHash: true,
        role: true,
        roles: true,

        school: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
        username: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: User })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateUser(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() data: UserUpdateInput
  ): Promise<User | null> {
    try {
      return await this.service.updateUser({
        where: params,
        data: {
          ...data,

          school: data.school
            ? {
                connect: data.school,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          email: true,
          firstName: true,
          id: true,
          isActive: true,
          lastLogin: true,
          lastName: true,
          passwordHash: true,
          role: true,
          roles: true,

          school: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
          username: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: User })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteUser(
    @common.Param() params: UserWhereUniqueInput
  ): Promise<User | null> {
    try {
      return await this.service.deleteUser({
        where: params,
        select: {
          createdAt: true,
          email: true,
          firstName: true,
          id: true,
          isActive: true,
          lastLogin: true,
          lastName: true,
          passwordHash: true,
          role: true,
          roles: true,

          school: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
          username: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/parentProfiles")
  @ApiNestedQuery(ParentProfileFindManyArgs)
  async findParentProfiles(
    @common.Req() request: Request,
    @common.Param() params: UserWhereUniqueInput
  ): Promise<ParentProfile[]> {
    const query = plainToClass(ParentProfileFindManyArgs, request.query);
    const results = await this.service.findParentProfiles(params.id, {
      ...query,
      select: {
        children: true,
        createdAt: true,
        id: true,
        occupation: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/parentProfiles")
  async connectParentProfiles(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: ParentProfileWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      parentProfiles: {
        connect: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/parentProfiles")
  async updateParentProfiles(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: ParentProfileWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      parentProfiles: {
        set: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/parentProfiles")
  async disconnectParentProfiles(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: ParentProfileWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      parentProfiles: {
        disconnect: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/studentProfiles")
  @ApiNestedQuery(StudentProfileFindManyArgs)
  async findStudentProfiles(
    @common.Req() request: Request,
    @common.Param() params: UserWhereUniqueInput
  ): Promise<StudentProfile[]> {
    const query = plainToClass(StudentProfileFindManyArgs, request.query);
    const results = await this.service.findStudentProfiles(params.id, {
      ...query,
      select: {
        admissionNo: true,

        classField: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        dateOfBirth: true,
        emergencyContacts: true,
        id: true,
        medicalInfo: true,
        rollNo: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/studentProfiles")
  async connectStudentProfiles(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: StudentProfileWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      studentProfiles: {
        connect: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/studentProfiles")
  async updateStudentProfiles(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: StudentProfileWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      studentProfiles: {
        set: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/studentProfiles")
  async disconnectStudentProfiles(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: StudentProfileWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      studentProfiles: {
        disconnect: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/teacherProfiles")
  @ApiNestedQuery(TeacherProfileFindManyArgs)
  async findTeacherProfiles(
    @common.Req() request: Request,
    @common.Param() params: UserWhereUniqueInput
  ): Promise<TeacherProfile[]> {
    const query = plainToClass(TeacherProfileFindManyArgs, request.query);
    const results = await this.service.findTeacherProfiles(params.id, {
      ...query,
      select: {
        createdAt: true,
        employeeId: true,
        id: true,
        joiningDate: true,
        qualifications: true,
        subjectsTaught: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/teacherProfiles")
  async connectTeacherProfiles(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: TeacherProfileWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      teacherProfiles: {
        connect: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/teacherProfiles")
  async updateTeacherProfiles(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: TeacherProfileWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      teacherProfiles: {
        set: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/teacherProfiles")
  async disconnectTeacherProfiles(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: TeacherProfileWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      teacherProfiles: {
        disconnect: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }
}
