/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";

import {
  Prisma,
  User as PrismaUser,
  ParentProfile as PrismaParentProfile,
  StudentProfile as PrismaStudentProfile,
  TeacherProfile as PrismaTeacherProfile,
  School as PrismaSchool,
} from "@prisma/client";

export class UserServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(args: Omit<Prisma.UserCountArgs, "select">): Promise<number> {
    return this.prisma.user.count(args);
  }

  async users(args: Prisma.UserFindManyArgs): Promise<PrismaUser[]> {
    return this.prisma.user.findMany(args);
  }
  async user(args: Prisma.UserFindUniqueArgs): Promise<PrismaUser | null> {
    return this.prisma.user.findUnique(args);
  }
  async createUser(args: Prisma.UserCreateArgs): Promise<PrismaUser> {
    return this.prisma.user.create(args);
  }
  async updateUser(args: Prisma.UserUpdateArgs): Promise<PrismaUser> {
    return this.prisma.user.update(args);
  }
  async deleteUser(args: Prisma.UserDeleteArgs): Promise<PrismaUser> {
    return this.prisma.user.delete(args);
  }

  async findParentProfiles(
    parentId: string,
    args: Prisma.ParentProfileFindManyArgs
  ): Promise<PrismaParentProfile[]> {
    return this.prisma.user
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .parentProfiles(args);
  }

  async findStudentProfiles(
    parentId: string,
    args: Prisma.StudentProfileFindManyArgs
  ): Promise<PrismaStudentProfile[]> {
    return this.prisma.user
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .studentProfiles(args);
  }

  async findTeacherProfiles(
    parentId: string,
    args: Prisma.TeacherProfileFindManyArgs
  ): Promise<PrismaTeacherProfile[]> {
    return this.prisma.user
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .teacherProfiles(args);
  }

  async getSchool(parentId: string): Promise<PrismaSchool | null> {
    return this.prisma.user
      .findUnique({
        where: { id: parentId },
      })
      .school();
  }
}
