/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { ParentProfile } from "./ParentProfile";
import { ParentProfileCountArgs } from "./ParentProfileCountArgs";
import { ParentProfileFindManyArgs } from "./ParentProfileFindManyArgs";
import { ParentProfileFindUniqueArgs } from "./ParentProfileFindUniqueArgs";
import { CreateParentProfileArgs } from "./CreateParentProfileArgs";
import { UpdateParentProfileArgs } from "./UpdateParentProfileArgs";
import { DeleteParentProfileArgs } from "./DeleteParentProfileArgs";
import { User } from "../../user/base/User";
import { ParentProfileService } from "../parentProfile.service";
@graphql.Resolver(() => ParentProfile)
export class ParentProfileResolverBase {
  constructor(protected readonly service: ParentProfileService) {}

  async _parentProfilesMeta(
    @graphql.Args() args: ParentProfileCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [ParentProfile])
  async parentProfiles(
    @graphql.Args() args: ParentProfileFindManyArgs
  ): Promise<ParentProfile[]> {
    return this.service.parentProfiles(args);
  }

  @graphql.Query(() => ParentProfile, { nullable: true })
  async parentProfile(
    @graphql.Args() args: ParentProfileFindUniqueArgs
  ): Promise<ParentProfile | null> {
    const result = await this.service.parentProfile(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => ParentProfile)
  async createParentProfile(
    @graphql.Args() args: CreateParentProfileArgs
  ): Promise<ParentProfile> {
    return await this.service.createParentProfile({
      ...args,
      data: {
        ...args.data,

        user: args.data.user
          ? {
              connect: args.data.user,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => ParentProfile)
  async updateParentProfile(
    @graphql.Args() args: UpdateParentProfileArgs
  ): Promise<ParentProfile | null> {
    try {
      return await this.service.updateParentProfile({
        ...args,
        data: {
          ...args.data,

          user: args.data.user
            ? {
                connect: args.data.user,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => ParentProfile)
  async deleteParentProfile(
    @graphql.Args() args: DeleteParentProfileArgs
  ): Promise<ParentProfile | null> {
    try {
      return await this.service.deleteParentProfile(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => User, {
    nullable: true,
    name: "user",
  })
  async getUser(@graphql.Parent() parent: ParentProfile): Promise<User | null> {
    const result = await this.service.getUser(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
