/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import {
  Prisma,
  ParentProfile as PrismaParentProfile,
  User as PrismaUser,
} from "@prisma/client";

export class ParentProfileServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.ParentProfileCountArgs, "select">
  ): Promise<number> {
    return this.prisma.parentProfile.count(args);
  }

  async parentProfiles(
    args: Prisma.ParentProfileFindManyArgs
  ): Promise<PrismaParentProfile[]> {
    return this.prisma.parentProfile.findMany(args);
  }
  async parentProfile(
    args: Prisma.ParentProfileFindUniqueArgs
  ): Promise<PrismaParentProfile | null> {
    return this.prisma.parentProfile.findUnique(args);
  }
  async createParentProfile(
    args: Prisma.ParentProfileCreateArgs
  ): Promise<PrismaParentProfile> {
    return this.prisma.parentProfile.create(args);
  }
  async updateParentProfile(
    args: Prisma.ParentProfileUpdateArgs
  ): Promise<PrismaParentProfile> {
    return this.prisma.parentProfile.update(args);
  }
  async deleteParentProfile(
    args: Prisma.ParentProfileDeleteArgs
  ): Promise<PrismaParentProfile> {
    return this.prisma.parentProfile.delete(args);
  }

  async getUser(parentId: string): Promise<PrismaUser | null> {
    return this.prisma.parentProfile
      .findUnique({
        where: { id: parentId },
      })
      .user();
  }
}
