/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { ParentProfileService } from "../parentProfile.service";
import { ParentProfileCreateInput } from "./ParentProfileCreateInput";
import { ParentProfile } from "./ParentProfile";
import { ParentProfileFindManyArgs } from "./ParentProfileFindManyArgs";
import { ParentProfileWhereUniqueInput } from "./ParentProfileWhereUniqueInput";
import { ParentProfileUpdateInput } from "./ParentProfileUpdateInput";

export class ParentProfileControllerBase {
  constructor(protected readonly service: ParentProfileService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: ParentProfile })
  async createParentProfile(
    @common.Body() data: ParentProfileCreateInput
  ): Promise<ParentProfile> {
    return await this.service.createParentProfile({
      data: {
        ...data,

        user: data.user
          ? {
              connect: data.user,
            }
          : undefined,
      },
      select: {
        children: true,
        createdAt: true,
        id: true,
        occupation: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [ParentProfile] })
  @ApiNestedQuery(ParentProfileFindManyArgs)
  async parentProfiles(
    @common.Req() request: Request
  ): Promise<ParentProfile[]> {
    const args = plainToClass(ParentProfileFindManyArgs, request.query);
    return this.service.parentProfiles({
      ...args,
      select: {
        children: true,
        createdAt: true,
        id: true,
        occupation: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: ParentProfile })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async parentProfile(
    @common.Param() params: ParentProfileWhereUniqueInput
  ): Promise<ParentProfile | null> {
    const result = await this.service.parentProfile({
      where: params,
      select: {
        children: true,
        createdAt: true,
        id: true,
        occupation: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: ParentProfile })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateParentProfile(
    @common.Param() params: ParentProfileWhereUniqueInput,
    @common.Body() data: ParentProfileUpdateInput
  ): Promise<ParentProfile | null> {
    try {
      return await this.service.updateParentProfile({
        where: params,
        data: {
          ...data,

          user: data.user
            ? {
                connect: data.user,
              }
            : undefined,
        },
        select: {
          children: true,
          createdAt: true,
          id: true,
          occupation: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: ParentProfile })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteParentProfile(
    @common.Param() params: ParentProfileWhereUniqueInput
  ): Promise<ParentProfile | null> {
    try {
      return await this.service.deleteParentProfile({
        where: params,
        select: {
          children: true,
          createdAt: true,
          id: true,
          occupation: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
