/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { FloatNullableFilter } from "../../util/FloatNullableFilter";
import { Type } from "class-transformer";
import { IsOptional, ValidateNested, IsEnum } from "class-validator";
import { FeeStructureWhereUniqueInput } from "../../feeStructure/base/FeeStructureWhereUniqueInput";
import { EnumTransactionGateway } from "./EnumTransactionGateway";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { StringFilter } from "../../util/StringFilter";
import { EnumTransactionPaymentMethod } from "./EnumTransactionPaymentMethod";
import { SchoolWhereUniqueInput } from "../../school/base/SchoolWhereUniqueInput";
import { EnumTransactionStatus } from "./EnumTransactionStatus";

@InputType()
class TransactionWhereInput {
  @ApiProperty({
    required: false,
    type: FloatNullableFilter,
  })
  @Type(() => FloatNullableFilter)
  @IsOptional()
  @Field(() => FloatNullableFilter, {
    nullable: true,
  })
  amount?: FloatNullableFilter;

  @ApiProperty({
    required: false,
    type: () => FeeStructureWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => FeeStructureWhereUniqueInput)
  @IsOptional()
  @Field(() => FeeStructureWhereUniqueInput, {
    nullable: true,
  })
  feeStructure?: FeeStructureWhereUniqueInput;

  @ApiProperty({
    required: false,
    enum: EnumTransactionGateway,
  })
  @IsEnum(EnumTransactionGateway)
  @IsOptional()
  @Field(() => EnumTransactionGateway, {
    nullable: true,
  })
  gateway?: "Option1";

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  gatewayTransactionId?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    enum: EnumTransactionPaymentMethod,
  })
  @IsEnum(EnumTransactionPaymentMethod)
  @IsOptional()
  @Field(() => EnumTransactionPaymentMethod, {
    nullable: true,
  })
  paymentMethod?: "Option1";

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  receiptUrl?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: () => SchoolWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => SchoolWhereUniqueInput)
  @IsOptional()
  @Field(() => SchoolWhereUniqueInput, {
    nullable: true,
  })
  school?: SchoolWhereUniqueInput;

  @ApiProperty({
    required: false,
    enum: EnumTransactionStatus,
  })
  @IsEnum(EnumTransactionStatus)
  @IsOptional()
  @Field(() => EnumTransactionStatus, {
    nullable: true,
  })
  status?: "Option1";

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  student?: StringNullableFilter;
}

export { TransactionWhereInput as TransactionWhereInput };
