/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";

import {
  IsNumber,
  Min,
  Max,
  IsOptional,
  ValidateNested,
  IsEnum,
  IsString,
  MaxLength,
} from "class-validator";

import { FeeStructureWhereUniqueInput } from "../../feeStructure/base/FeeStructureWhereUniqueInput";
import { Type } from "class-transformer";
import { EnumTransactionGateway } from "./EnumTransactionGateway";
import { EnumTransactionPaymentMethod } from "./EnumTransactionPaymentMethod";
import { SchoolWhereUniqueInput } from "../../school/base/SchoolWhereUniqueInput";
import { EnumTransactionStatus } from "./EnumTransactionStatus";

@InputType()
class TransactionUpdateInput {
  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Min(-999999999)
  @Max(999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  amount?: number | null;

  @ApiProperty({
    required: false,
    type: () => FeeStructureWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => FeeStructureWhereUniqueInput)
  @IsOptional()
  @Field(() => FeeStructureWhereUniqueInput, {
    nullable: true,
  })
  feeStructure?: FeeStructureWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    enum: EnumTransactionGateway,
  })
  @IsEnum(EnumTransactionGateway)
  @IsOptional()
  @Field(() => EnumTransactionGateway, {
    nullable: true,
  })
  gateway?: "Option1" | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  gatewayTransactionId?: string | null;

  @ApiProperty({
    required: false,
    enum: EnumTransactionPaymentMethod,
  })
  @IsEnum(EnumTransactionPaymentMethod)
  @IsOptional()
  @Field(() => EnumTransactionPaymentMethod, {
    nullable: true,
  })
  paymentMethod?: "Option1" | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  receiptUrl?: string | null;

  @ApiProperty({
    required: false,
    type: () => SchoolWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => SchoolWhereUniqueInput)
  @IsOptional()
  @Field(() => SchoolWhereUniqueInput, {
    nullable: true,
  })
  school?: SchoolWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    enum: EnumTransactionStatus,
  })
  @IsEnum(EnumTransactionStatus)
  @IsOptional()
  @Field(() => EnumTransactionStatus, {
    nullable: true,
  })
  status?: "Option1" | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  student?: string | null;
}

export { TransactionUpdateInput as TransactionUpdateInput };
