/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { TeacherProfile } from "./TeacherProfile";
import { TeacherProfileCountArgs } from "./TeacherProfileCountArgs";
import { TeacherProfileFindManyArgs } from "./TeacherProfileFindManyArgs";
import { TeacherProfileFindUniqueArgs } from "./TeacherProfileFindUniqueArgs";
import { CreateTeacherProfileArgs } from "./CreateTeacherProfileArgs";
import { UpdateTeacherProfileArgs } from "./UpdateTeacherProfileArgs";
import { DeleteTeacherProfileArgs } from "./DeleteTeacherProfileArgs";
import { User } from "../../user/base/User";
import { TeacherProfileService } from "../teacherProfile.service";
@graphql.Resolver(() => TeacherProfile)
export class TeacherProfileResolverBase {
  constructor(protected readonly service: TeacherProfileService) {}

  async _teacherProfilesMeta(
    @graphql.Args() args: TeacherProfileCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [TeacherProfile])
  async teacherProfiles(
    @graphql.Args() args: TeacherProfileFindManyArgs
  ): Promise<TeacherProfile[]> {
    return this.service.teacherProfiles(args);
  }

  @graphql.Query(() => TeacherProfile, { nullable: true })
  async teacherProfile(
    @graphql.Args() args: TeacherProfileFindUniqueArgs
  ): Promise<TeacherProfile | null> {
    const result = await this.service.teacherProfile(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => TeacherProfile)
  async createTeacherProfile(
    @graphql.Args() args: CreateTeacherProfileArgs
  ): Promise<TeacherProfile> {
    return await this.service.createTeacherProfile({
      ...args,
      data: {
        ...args.data,

        user: args.data.user
          ? {
              connect: args.data.user,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => TeacherProfile)
  async updateTeacherProfile(
    @graphql.Args() args: UpdateTeacherProfileArgs
  ): Promise<TeacherProfile | null> {
    try {
      return await this.service.updateTeacherProfile({
        ...args,
        data: {
          ...args.data,

          user: args.data.user
            ? {
                connect: args.data.user,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => TeacherProfile)
  async deleteTeacherProfile(
    @graphql.Args() args: DeleteTeacherProfileArgs
  ): Promise<TeacherProfile | null> {
    try {
      return await this.service.deleteTeacherProfile(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => User, {
    nullable: true,
    name: "user",
  })
  async getUser(
    @graphql.Parent() parent: TeacherProfile
  ): Promise<User | null> {
    const result = await this.service.getUser(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
