/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import {
  Prisma,
  TeacherProfile as PrismaTeacherProfile,
  User as PrismaUser,
} from "@prisma/client";

export class TeacherProfileServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.TeacherProfileCountArgs, "select">
  ): Promise<number> {
    return this.prisma.teacherProfile.count(args);
  }

  async teacherProfiles(
    args: Prisma.TeacherProfileFindManyArgs
  ): Promise<PrismaTeacherProfile[]> {
    return this.prisma.teacherProfile.findMany(args);
  }
  async teacherProfile(
    args: Prisma.TeacherProfileFindUniqueArgs
  ): Promise<PrismaTeacherProfile | null> {
    return this.prisma.teacherProfile.findUnique(args);
  }
  async createTeacherProfile(
    args: Prisma.TeacherProfileCreateArgs
  ): Promise<PrismaTeacherProfile> {
    return this.prisma.teacherProfile.create(args);
  }
  async updateTeacherProfile(
    args: Prisma.TeacherProfileUpdateArgs
  ): Promise<PrismaTeacherProfile> {
    return this.prisma.teacherProfile.update(args);
  }
  async deleteTeacherProfile(
    args: Prisma.TeacherProfileDeleteArgs
  ): Promise<PrismaTeacherProfile> {
    return this.prisma.teacherProfile.delete(args);
  }

  async getUser(parentId: string): Promise<PrismaUser | null> {
    return this.prisma.teacherProfile
      .findUnique({
        where: { id: parentId },
      })
      .user();
  }
}
