/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { TeacherProfileService } from "../teacherProfile.service";
import { TeacherProfileCreateInput } from "./TeacherProfileCreateInput";
import { TeacherProfile } from "./TeacherProfile";
import { TeacherProfileFindManyArgs } from "./TeacherProfileFindManyArgs";
import { TeacherProfileWhereUniqueInput } from "./TeacherProfileWhereUniqueInput";
import { TeacherProfileUpdateInput } from "./TeacherProfileUpdateInput";

export class TeacherProfileControllerBase {
  constructor(protected readonly service: TeacherProfileService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: TeacherProfile })
  async createTeacherProfile(
    @common.Body() data: TeacherProfileCreateInput
  ): Promise<TeacherProfile> {
    return await this.service.createTeacherProfile({
      data: {
        ...data,

        user: data.user
          ? {
              connect: data.user,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        employeeId: true,
        id: true,
        joiningDate: true,
        qualifications: true,
        subjectsTaught: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [TeacherProfile] })
  @ApiNestedQuery(TeacherProfileFindManyArgs)
  async teacherProfiles(
    @common.Req() request: Request
  ): Promise<TeacherProfile[]> {
    const args = plainToClass(TeacherProfileFindManyArgs, request.query);
    return this.service.teacherProfiles({
      ...args,
      select: {
        createdAt: true,
        employeeId: true,
        id: true,
        joiningDate: true,
        qualifications: true,
        subjectsTaught: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: TeacherProfile })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async teacherProfile(
    @common.Param() params: TeacherProfileWhereUniqueInput
  ): Promise<TeacherProfile | null> {
    const result = await this.service.teacherProfile({
      where: params,
      select: {
        createdAt: true,
        employeeId: true,
        id: true,
        joiningDate: true,
        qualifications: true,
        subjectsTaught: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: TeacherProfile })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateTeacherProfile(
    @common.Param() params: TeacherProfileWhereUniqueInput,
    @common.Body() data: TeacherProfileUpdateInput
  ): Promise<TeacherProfile | null> {
    try {
      return await this.service.updateTeacherProfile({
        where: params,
        data: {
          ...data,

          user: data.user
            ? {
                connect: data.user,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          employeeId: true,
          id: true,
          joiningDate: true,
          qualifications: true,
          subjectsTaught: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: TeacherProfile })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteTeacherProfile(
    @common.Param() params: TeacherProfileWhereUniqueInput
  ): Promise<TeacherProfile | null> {
    try {
      return await this.service.deleteTeacherProfile({
        where: params,
        select: {
          createdAt: true,
          employeeId: true,
          id: true,
          joiningDate: true,
          qualifications: true,
          subjectsTaught: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
