/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ObjectType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { ClassModel } from "../../classModel/base/ClassModel";
import {
  ValidateNested,
  IsOptional,
  IsDate,
  IsString,
  MaxLength,
  IsEnum,
} from "class-validator";
import { Type } from "class-transformer";
import { School } from "../../school/base/School";
import { EnumAttendanceSession } from "./EnumAttendanceSession";
import { EnumAttendanceStatus } from "./EnumAttendanceStatus";

@ObjectType()
class Attendance {
  @ApiProperty({
    required: false,
    type: () => ClassModel,
  })
  @ValidateNested()
  @Type(() => ClassModel)
  @IsOptional()
  classField?: ClassModel | null;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  createdAt!: Date;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  date!: Date | null;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  id!: string;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  markedBy!: string | null;

  @ApiProperty({
    required: false,
    type: () => School,
  })
  @ValidateNested()
  @Type(() => School)
  @IsOptional()
  school?: School | null;

  @ApiProperty({
    required: false,
    enum: EnumAttendanceSession,
  })
  @IsEnum(EnumAttendanceSession)
  @IsOptional()
  @Field(() => EnumAttendanceSession, {
    nullable: true,
  })
  session?: "Option1" | null;

  @ApiProperty({
    required: false,
    enum: EnumAttendanceStatus,
  })
  @IsEnum(EnumAttendanceStatus)
  @IsOptional()
  @Field(() => EnumAttendanceStatus, {
    nullable: true,
  })
  status?: "Option1" | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  student!: string | null;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  updatedAt!: Date;
}

export { Attendance as Attendance };
