/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { ClassModelWhereUniqueInput } from "../../classModel/base/ClassModelWhereUniqueInput";
import { ValidateNested, IsOptional, IsEnum } from "class-validator";
import { Type } from "class-transformer";
import { DateTimeNullableFilter } from "../../util/DateTimeNullableFilter";
import { StringFilter } from "../../util/StringFilter";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { SchoolWhereUniqueInput } from "../../school/base/SchoolWhereUniqueInput";
import { EnumAttendanceSession } from "./EnumAttendanceSession";
import { EnumAttendanceStatus } from "./EnumAttendanceStatus";

@InputType()
class AttendanceWhereInput {
  @ApiProperty({
    required: false,
    type: () => ClassModelWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => ClassModelWhereUniqueInput)
  @IsOptional()
  @Field(() => ClassModelWhereUniqueInput, {
    nullable: true,
  })
  classField?: ClassModelWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: DateTimeNullableFilter,
  })
  @Type(() => DateTimeNullableFilter)
  @IsOptional()
  @Field(() => DateTimeNullableFilter, {
    nullable: true,
  })
  date?: DateTimeNullableFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  markedBy?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: () => SchoolWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => SchoolWhereUniqueInput)
  @IsOptional()
  @Field(() => SchoolWhereUniqueInput, {
    nullable: true,
  })
  school?: SchoolWhereUniqueInput;

  @ApiProperty({
    required: false,
    enum: EnumAttendanceSession,
  })
  @IsEnum(EnumAttendanceSession)
  @IsOptional()
  @Field(() => EnumAttendanceSession, {
    nullable: true,
  })
  session?: "Option1";

  @ApiProperty({
    required: false,
    enum: EnumAttendanceStatus,
  })
  @IsEnum(EnumAttendanceStatus)
  @IsOptional()
  @Field(() => EnumAttendanceStatus, {
    nullable: true,
  })
  status?: "Option1";

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  student?: StringNullableFilter;
}

export { AttendanceWhereInput as AttendanceWhereInput };
