/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { AnnouncementUpdateManyWithoutSchoolsInput } from "./AnnouncementUpdateManyWithoutSchoolsInput";
import {
  ValidateNested,
  IsOptional,
  IsString,
  MaxLength,
  IsEnum,
} from "class-validator";
import { Type } from "class-transformer";
import { AttendanceUpdateManyWithoutSchoolsInput } from "./AttendanceUpdateManyWithoutSchoolsInput";
import { ClassModelUpdateManyWithoutSchoolsInput } from "./ClassModelUpdateManyWithoutSchoolsInput";
import { IsJSONValue } from "../../validators";
import { GraphQLJSON } from "graphql-type-json";
import { InputJsonValue } from "../../types";
import { FeeStructureUpdateManyWithoutSchoolsInput } from "./FeeStructureUpdateManyWithoutSchoolsInput";
import { GradeUpdateManyWithoutSchoolsInput } from "./GradeUpdateManyWithoutSchoolsInput";
import { MessageUpdateManyWithoutSchoolsInput } from "./MessageUpdateManyWithoutSchoolsInput";
import { SubjectUpdateManyWithoutSchoolsInput } from "./SubjectUpdateManyWithoutSchoolsInput";
import { EnumSchoolSubscriptionTier } from "./EnumSchoolSubscriptionTier";
import { TransactionUpdateManyWithoutSchoolsInput } from "./TransactionUpdateManyWithoutSchoolsInput";
import { UserUpdateManyWithoutSchoolsInput } from "./UserUpdateManyWithoutSchoolsInput";

@InputType()
class SchoolUpdateInput {
  @ApiProperty({
    required: false,
    type: () => AnnouncementUpdateManyWithoutSchoolsInput,
  })
  @ValidateNested()
  @Type(() => AnnouncementUpdateManyWithoutSchoolsInput)
  @IsOptional()
  @Field(() => AnnouncementUpdateManyWithoutSchoolsInput, {
    nullable: true,
  })
  announcements?: AnnouncementUpdateManyWithoutSchoolsInput;

  @ApiProperty({
    required: false,
    type: () => AttendanceUpdateManyWithoutSchoolsInput,
  })
  @ValidateNested()
  @Type(() => AttendanceUpdateManyWithoutSchoolsInput)
  @IsOptional()
  @Field(() => AttendanceUpdateManyWithoutSchoolsInput, {
    nullable: true,
  })
  attendances?: AttendanceUpdateManyWithoutSchoolsInput;

  @ApiProperty({
    required: false,
    type: () => ClassModelUpdateManyWithoutSchoolsInput,
  })
  @ValidateNested()
  @Type(() => ClassModelUpdateManyWithoutSchoolsInput)
  @IsOptional()
  @Field(() => ClassModelUpdateManyWithoutSchoolsInput, {
    nullable: true,
  })
  classes?: ClassModelUpdateManyWithoutSchoolsInput;

  @ApiProperty({
    required: false,
  })
  @IsJSONValue()
  @IsOptional()
  @Field(() => GraphQLJSON, {
    nullable: true,
  })
  configField?: InputJsonValue;

  @ApiProperty({
    required: false,
    type: () => FeeStructureUpdateManyWithoutSchoolsInput,
  })
  @ValidateNested()
  @Type(() => FeeStructureUpdateManyWithoutSchoolsInput)
  @IsOptional()
  @Field(() => FeeStructureUpdateManyWithoutSchoolsInput, {
    nullable: true,
  })
  feeStructures?: FeeStructureUpdateManyWithoutSchoolsInput;

  @ApiProperty({
    required: false,
    type: () => GradeUpdateManyWithoutSchoolsInput,
  })
  @ValidateNested()
  @Type(() => GradeUpdateManyWithoutSchoolsInput)
  @IsOptional()
  @Field(() => GradeUpdateManyWithoutSchoolsInput, {
    nullable: true,
  })
  grades?: GradeUpdateManyWithoutSchoolsInput;

  @ApiProperty({
    required: false,
    type: () => MessageUpdateManyWithoutSchoolsInput,
  })
  @ValidateNested()
  @Type(() => MessageUpdateManyWithoutSchoolsInput)
  @IsOptional()
  @Field(() => MessageUpdateManyWithoutSchoolsInput, {
    nullable: true,
  })
  messages?: MessageUpdateManyWithoutSchoolsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  subdomain?: string | null;

  @ApiProperty({
    required: false,
    type: () => SubjectUpdateManyWithoutSchoolsInput,
  })
  @ValidateNested()
  @Type(() => SubjectUpdateManyWithoutSchoolsInput)
  @IsOptional()
  @Field(() => SubjectUpdateManyWithoutSchoolsInput, {
    nullable: true,
  })
  subjects?: SubjectUpdateManyWithoutSchoolsInput;

  @ApiProperty({
    required: false,
    enum: EnumSchoolSubscriptionTier,
  })
  @IsEnum(EnumSchoolSubscriptionTier)
  @IsOptional()
  @Field(() => EnumSchoolSubscriptionTier, {
    nullable: true,
  })
  subscriptionTier?: "Option1" | null;

  @ApiProperty({
    required: false,
    type: () => TransactionUpdateManyWithoutSchoolsInput,
  })
  @ValidateNested()
  @Type(() => TransactionUpdateManyWithoutSchoolsInput)
  @IsOptional()
  @Field(() => TransactionUpdateManyWithoutSchoolsInput, {
    nullable: true,
  })
  transactions?: TransactionUpdateManyWithoutSchoolsInput;

  @ApiProperty({
    required: false,
    type: () => UserUpdateManyWithoutSchoolsInput,
  })
  @ValidateNested()
  @Type(() => UserUpdateManyWithoutSchoolsInput)
  @IsOptional()
  @Field(() => UserUpdateManyWithoutSchoolsInput, {
    nullable: true,
  })
  users?: UserUpdateManyWithoutSchoolsInput;
}

export { SchoolUpdateInput as SchoolUpdateInput };
