/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { AnnouncementListRelationFilter } from "../../announcement/base/AnnouncementListRelationFilter";
import { ValidateNested, IsOptional, IsEnum } from "class-validator";
import { Type } from "class-transformer";
import { AttendanceListRelationFilter } from "../../attendance/base/AttendanceListRelationFilter";
import { ClassModelListRelationFilter } from "../../classModel/base/ClassModelListRelationFilter";
import { JsonFilter } from "../../util/JsonFilter";
import { FeeStructureListRelationFilter } from "../../feeStructure/base/FeeStructureListRelationFilter";
import { GradeListRelationFilter } from "../../grade/base/GradeListRelationFilter";
import { StringFilter } from "../../util/StringFilter";
import { MessageListRelationFilter } from "../../message/base/MessageListRelationFilter";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { SubjectListRelationFilter } from "../../subject/base/SubjectListRelationFilter";
import { EnumSchoolSubscriptionTier } from "./EnumSchoolSubscriptionTier";
import { TransactionListRelationFilter } from "../../transaction/base/TransactionListRelationFilter";
import { UserListRelationFilter } from "../../user/base/UserListRelationFilter";

@InputType()
class SchoolWhereInput {
  @ApiProperty({
    required: false,
    type: () => AnnouncementListRelationFilter,
  })
  @ValidateNested()
  @Type(() => AnnouncementListRelationFilter)
  @IsOptional()
  @Field(() => AnnouncementListRelationFilter, {
    nullable: true,
  })
  announcements?: AnnouncementListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => AttendanceListRelationFilter,
  })
  @ValidateNested()
  @Type(() => AttendanceListRelationFilter)
  @IsOptional()
  @Field(() => AttendanceListRelationFilter, {
    nullable: true,
  })
  attendances?: AttendanceListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => ClassModelListRelationFilter,
  })
  @ValidateNested()
  @Type(() => ClassModelListRelationFilter)
  @IsOptional()
  @Field(() => ClassModelListRelationFilter, {
    nullable: true,
  })
  classes?: ClassModelListRelationFilter;

  @ApiProperty({
    required: false,
    type: JsonFilter,
  })
  @Type(() => JsonFilter)
  @IsOptional()
  @Field(() => JsonFilter, {
    nullable: true,
  })
  configField?: JsonFilter;

  @ApiProperty({
    required: false,
    type: () => FeeStructureListRelationFilter,
  })
  @ValidateNested()
  @Type(() => FeeStructureListRelationFilter)
  @IsOptional()
  @Field(() => FeeStructureListRelationFilter, {
    nullable: true,
  })
  feeStructures?: FeeStructureListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => GradeListRelationFilter,
  })
  @ValidateNested()
  @Type(() => GradeListRelationFilter)
  @IsOptional()
  @Field(() => GradeListRelationFilter, {
    nullable: true,
  })
  grades?: GradeListRelationFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: () => MessageListRelationFilter,
  })
  @ValidateNested()
  @Type(() => MessageListRelationFilter)
  @IsOptional()
  @Field(() => MessageListRelationFilter, {
    nullable: true,
  })
  messages?: MessageListRelationFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  name?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  subdomain?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: () => SubjectListRelationFilter,
  })
  @ValidateNested()
  @Type(() => SubjectListRelationFilter)
  @IsOptional()
  @Field(() => SubjectListRelationFilter, {
    nullable: true,
  })
  subjects?: SubjectListRelationFilter;

  @ApiProperty({
    required: false,
    enum: EnumSchoolSubscriptionTier,
  })
  @IsEnum(EnumSchoolSubscriptionTier)
  @IsOptional()
  @Field(() => EnumSchoolSubscriptionTier, {
    nullable: true,
  })
  subscriptionTier?: "Option1";

  @ApiProperty({
    required: false,
    type: () => TransactionListRelationFilter,
  })
  @ValidateNested()
  @Type(() => TransactionListRelationFilter)
  @IsOptional()
  @Field(() => TransactionListRelationFilter, {
    nullable: true,
  })
  transactions?: TransactionListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => UserListRelationFilter,
  })
  @ValidateNested()
  @Type(() => UserListRelationFilter)
  @IsOptional()
  @Field(() => UserListRelationFilter, {
    nullable: true,
  })
  users?: UserListRelationFilter;
}

export { SchoolWhereInput as SchoolWhereInput };
