/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ObjectType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { Announcement } from "../../announcement/base/Announcement";
import {
  ValidateNested,
  IsOptional,
  IsDate,
  IsString,
  MaxLength,
  IsEnum,
} from "class-validator";
import { Type } from "class-transformer";
import { Attendance } from "../../attendance/base/Attendance";
import { ClassModel } from "../../classModel/base/ClassModel";
import { IsJSONValue } from "../../validators";
import { GraphQLJSON } from "graphql-type-json";
import { JsonValue } from "type-fest";
import { FeeStructure } from "../../feeStructure/base/FeeStructure";
import { Grade } from "../../grade/base/Grade";
import { Message } from "../../message/base/Message";
import { Subject } from "../../subject/base/Subject";
import { EnumSchoolSubscriptionTier } from "./EnumSchoolSubscriptionTier";
import { Transaction } from "../../transaction/base/Transaction";
import { User } from "../../user/base/User";

@ObjectType()
class School {
  @ApiProperty({
    required: false,
    type: () => [Announcement],
  })
  @ValidateNested()
  @Type(() => Announcement)
  @IsOptional()
  announcements?: Array<Announcement>;

  @ApiProperty({
    required: false,
    type: () => [Attendance],
  })
  @ValidateNested()
  @Type(() => Attendance)
  @IsOptional()
  attendances?: Array<Attendance>;

  @ApiProperty({
    required: false,
    type: () => [ClassModel],
  })
  @ValidateNested()
  @Type(() => ClassModel)
  @IsOptional()
  classes?: Array<ClassModel>;

  @ApiProperty({
    required: false,
  })
  @IsJSONValue()
  @IsOptional()
  @Field(() => GraphQLJSON, {
    nullable: true,
  })
  configField!: JsonValue;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  createdAt!: Date;

  @ApiProperty({
    required: false,
    type: () => [FeeStructure],
  })
  @ValidateNested()
  @Type(() => FeeStructure)
  @IsOptional()
  feeStructures?: Array<FeeStructure>;

  @ApiProperty({
    required: false,
    type: () => [Grade],
  })
  @ValidateNested()
  @Type(() => Grade)
  @IsOptional()
  grades?: Array<Grade>;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  id!: string;

  @ApiProperty({
    required: false,
    type: () => [Message],
  })
  @ValidateNested()
  @Type(() => Message)
  @IsOptional()
  messages?: Array<Message>;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name!: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  subdomain!: string | null;

  @ApiProperty({
    required: false,
    type: () => [Subject],
  })
  @ValidateNested()
  @Type(() => Subject)
  @IsOptional()
  subjects?: Array<Subject>;

  @ApiProperty({
    required: false,
    enum: EnumSchoolSubscriptionTier,
  })
  @IsEnum(EnumSchoolSubscriptionTier)
  @IsOptional()
  @Field(() => EnumSchoolSubscriptionTier, {
    nullable: true,
  })
  subscriptionTier?: "Option1" | null;

  @ApiProperty({
    required: false,
    type: () => [Transaction],
  })
  @ValidateNested()
  @Type(() => Transaction)
  @IsOptional()
  transactions?: Array<Transaction>;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  updatedAt!: Date;

  @ApiProperty({
    required: false,
    type: () => [User],
  })
  @ValidateNested()
  @Type(() => User)
  @IsOptional()
  users?: Array<User>;
}

export { School as School };
