/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { SchoolService } from "../school.service";
import { SchoolCreateInput } from "./SchoolCreateInput";
import { School } from "./School";
import { SchoolFindManyArgs } from "./SchoolFindManyArgs";
import { SchoolWhereUniqueInput } from "./SchoolWhereUniqueInput";
import { SchoolUpdateInput } from "./SchoolUpdateInput";
import { AnnouncementFindManyArgs } from "../../announcement/base/AnnouncementFindManyArgs";
import { Announcement } from "../../announcement/base/Announcement";
import { AnnouncementWhereUniqueInput } from "../../announcement/base/AnnouncementWhereUniqueInput";
import { AttendanceFindManyArgs } from "../../attendance/base/AttendanceFindManyArgs";
import { Attendance } from "../../attendance/base/Attendance";
import { AttendanceWhereUniqueInput } from "../../attendance/base/AttendanceWhereUniqueInput";
import { ClassModelFindManyArgs } from "../../classModel/base/ClassModelFindManyArgs";
import { ClassModel } from "../../classModel/base/ClassModel";
import { ClassModelWhereUniqueInput } from "../../classModel/base/ClassModelWhereUniqueInput";
import { FeeStructureFindManyArgs } from "../../feeStructure/base/FeeStructureFindManyArgs";
import { FeeStructure } from "../../feeStructure/base/FeeStructure";
import { FeeStructureWhereUniqueInput } from "../../feeStructure/base/FeeStructureWhereUniqueInput";
import { GradeFindManyArgs } from "../../grade/base/GradeFindManyArgs";
import { Grade } from "../../grade/base/Grade";
import { GradeWhereUniqueInput } from "../../grade/base/GradeWhereUniqueInput";
import { MessageFindManyArgs } from "../../message/base/MessageFindManyArgs";
import { Message } from "../../message/base/Message";
import { MessageWhereUniqueInput } from "../../message/base/MessageWhereUniqueInput";
import { SubjectFindManyArgs } from "../../subject/base/SubjectFindManyArgs";
import { Subject } from "../../subject/base/Subject";
import { SubjectWhereUniqueInput } from "../../subject/base/SubjectWhereUniqueInput";
import { TransactionFindManyArgs } from "../../transaction/base/TransactionFindManyArgs";
import { Transaction } from "../../transaction/base/Transaction";
import { TransactionWhereUniqueInput } from "../../transaction/base/TransactionWhereUniqueInput";
import { UserFindManyArgs } from "../../user/base/UserFindManyArgs";
import { User } from "../../user/base/User";
import { UserWhereUniqueInput } from "../../user/base/UserWhereUniqueInput";

export class SchoolControllerBase {
  constructor(protected readonly service: SchoolService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: School })
  async createSchool(@common.Body() data: SchoolCreateInput): Promise<School> {
    return await this.service.createSchool({
      data: data,
      select: {
        configField: true,
        createdAt: true,
        id: true,
        name: true,
        subdomain: true,
        subscriptionTier: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [School] })
  @ApiNestedQuery(SchoolFindManyArgs)
  async schools(@common.Req() request: Request): Promise<School[]> {
    const args = plainToClass(SchoolFindManyArgs, request.query);
    return this.service.schools({
      ...args,
      select: {
        configField: true,
        createdAt: true,
        id: true,
        name: true,
        subdomain: true,
        subscriptionTier: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: School })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async school(
    @common.Param() params: SchoolWhereUniqueInput
  ): Promise<School | null> {
    const result = await this.service.school({
      where: params,
      select: {
        configField: true,
        createdAt: true,
        id: true,
        name: true,
        subdomain: true,
        subscriptionTier: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: School })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateSchool(
    @common.Param() params: SchoolWhereUniqueInput,
    @common.Body() data: SchoolUpdateInput
  ): Promise<School | null> {
    try {
      return await this.service.updateSchool({
        where: params,
        data: data,
        select: {
          configField: true,
          createdAt: true,
          id: true,
          name: true,
          subdomain: true,
          subscriptionTier: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: School })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteSchool(
    @common.Param() params: SchoolWhereUniqueInput
  ): Promise<School | null> {
    try {
      return await this.service.deleteSchool({
        where: params,
        select: {
          configField: true,
          createdAt: true,
          id: true,
          name: true,
          subdomain: true,
          subscriptionTier: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/announcements")
  @ApiNestedQuery(AnnouncementFindManyArgs)
  async findAnnouncements(
    @common.Req() request: Request,
    @common.Param() params: SchoolWhereUniqueInput
  ): Promise<Announcement[]> {
    const query = plainToClass(AnnouncementFindManyArgs, request.query);
    const results = await this.service.findAnnouncements(params.id, {
      ...query,
      select: {
        attachments: true,
        audience: true,
        classIds: true,
        content: true,
        createdAt: true,
        id: true,
        priority: true,

        school: {
          select: {
            id: true,
          },
        },

        title: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/announcements")
  async connectAnnouncements(
    @common.Param() params: SchoolWhereUniqueInput,
    @common.Body() body: AnnouncementWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      announcements: {
        connect: body,
      },
    };
    await this.service.updateSchool({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/announcements")
  async updateAnnouncements(
    @common.Param() params: SchoolWhereUniqueInput,
    @common.Body() body: AnnouncementWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      announcements: {
        set: body,
      },
    };
    await this.service.updateSchool({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/announcements")
  async disconnectAnnouncements(
    @common.Param() params: SchoolWhereUniqueInput,
    @common.Body() body: AnnouncementWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      announcements: {
        disconnect: body,
      },
    };
    await this.service.updateSchool({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/attendances")
  @ApiNestedQuery(AttendanceFindManyArgs)
  async findAttendances(
    @common.Req() request: Request,
    @common.Param() params: SchoolWhereUniqueInput
  ): Promise<Attendance[]> {
    const query = plainToClass(AttendanceFindManyArgs, request.query);
    const results = await this.service.findAttendances(params.id, {
      ...query,
      select: {
        classField: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        date: true,
        id: true,
        markedBy: true,

        school: {
          select: {
            id: true,
          },
        },

        session: true,
        status: true,
        student: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/attendances")
  async connectAttendances(
    @common.Param() params: SchoolWhereUniqueInput,
    @common.Body() body: AttendanceWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      attendances: {
        connect: body,
      },
    };
    await this.service.updateSchool({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/attendances")
  async updateAttendances(
    @common.Param() params: SchoolWhereUniqueInput,
    @common.Body() body: AttendanceWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      attendances: {
        set: body,
      },
    };
    await this.service.updateSchool({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/attendances")
  async disconnectAttendances(
    @common.Param() params: SchoolWhereUniqueInput,
    @common.Body() body: AttendanceWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      attendances: {
        disconnect: body,
      },
    };
    await this.service.updateSchool({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/classes")
  @ApiNestedQuery(ClassModelFindManyArgs)
  async findClasses(
    @common.Req() request: Request,
    @common.Param() params: SchoolWhereUniqueInput
  ): Promise<ClassModel[]> {
    const query = plainToClass(ClassModelFindManyArgs, request.query);
    const results = await this.service.findClasses(params.id, {
      ...query,
      select: {
        academicYear: true,
        capacity: true,
        classTeacher: true,
        createdAt: true,
        id: true,
        name: true,

        school: {
          select: {
            id: true,
          },
        },

        section: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/classes")
  async connectClasses(
    @common.Param() params: SchoolWhereUniqueInput,
    @common.Body() body: ClassModelWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      classes: {
        connect: body,
      },
    };
    await this.service.updateSchool({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/classes")
  async updateClasses(
    @common.Param() params: SchoolWhereUniqueInput,
    @common.Body() body: ClassModelWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      classes: {
        set: body,
      },
    };
    await this.service.updateSchool({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/classes")
  async disconnectClasses(
    @common.Param() params: SchoolWhereUniqueInput,
    @common.Body() body: ClassModelWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      classes: {
        disconnect: body,
      },
    };
    await this.service.updateSchool({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/feeStructures")
  @ApiNestedQuery(FeeStructureFindManyArgs)
  async findFeeStructures(
    @common.Req() request: Request,
    @common.Param() params: SchoolWhereUniqueInput
  ): Promise<FeeStructure[]> {
    const query = plainToClass(FeeStructureFindManyArgs, request.query);
    const results = await this.service.findFeeStructures(params.id, {
      ...query,
      select: {
        amount: true,
        applicableClassIds: true,
        category: true,
        createdAt: true,
        dueDates: true,
        id: true,
        installmentCount: true,
        name: true,

        school: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/feeStructures")
  async connectFeeStructures(
    @common.Param() params: SchoolWhereUniqueInput,
    @common.Body() body: FeeStructureWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      feeStructures: {
        connect: body,
      },
    };
    await this.service.updateSchool({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/feeStructures")
  async updateFeeStructures(
    @common.Param() params: SchoolWhereUniqueInput,
    @common.Body() body: FeeStructureWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      feeStructures: {
        set: body,
      },
    };
    await this.service.updateSchool({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/feeStructures")
  async disconnectFeeStructures(
    @common.Param() params: SchoolWhereUniqueInput,
    @common.Body() body: FeeStructureWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      feeStructures: {
        disconnect: body,
      },
    };
    await this.service.updateSchool({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/grades")
  @ApiNestedQuery(GradeFindManyArgs)
  async findGrades(
    @common.Req() request: Request,
    @common.Param() params: SchoolWhereUniqueInput
  ): Promise<Grade[]> {
    const query = plainToClass(GradeFindManyArgs, request.query);
    const results = await this.service.findGrades(params.id, {
      ...query,
      select: {
        assessmentType: true,
        comments: true,
        createdAt: true,
        grade: true,
        id: true,
        maxScore: true,
        published: true,

        school: {
          select: {
            id: true,
          },
        },

        score: true,
        student: true,

        subject: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/grades")
  async connectGrades(
    @common.Param() params: SchoolWhereUniqueInput,
    @common.Body() body: GradeWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      grades: {
        connect: body,
      },
    };
    await this.service.updateSchool({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/grades")
  async updateGrades(
    @common.Param() params: SchoolWhereUniqueInput,
    @common.Body() body: GradeWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      grades: {
        set: body,
      },
    };
    await this.service.updateSchool({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/grades")
  async disconnectGrades(
    @common.Param() params: SchoolWhereUniqueInput,
    @common.Body() body: GradeWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      grades: {
        disconnect: body,
      },
    };
    await this.service.updateSchool({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/messages")
  @ApiNestedQuery(MessageFindManyArgs)
  async findMessages(
    @common.Req() request: Request,
    @common.Param() params: SchoolWhereUniqueInput
  ): Promise<Message[]> {
    const query = plainToClass(MessageFindManyArgs, request.query);
    const results = await this.service.findMessages(params.id, {
      ...query,
      select: {
        attachmentUrl: true,
        content: true,
        createdAt: true,
        id: true,
        read: true,
        readAt: true,
        recipient: true,

        school: {
          select: {
            id: true,
          },
        },

        sender: true,
        typeField: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/messages")
  async connectMessages(
    @common.Param() params: SchoolWhereUniqueInput,
    @common.Body() body: MessageWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      messages: {
        connect: body,
      },
    };
    await this.service.updateSchool({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/messages")
  async updateMessages(
    @common.Param() params: SchoolWhereUniqueInput,
    @common.Body() body: MessageWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      messages: {
        set: body,
      },
    };
    await this.service.updateSchool({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/messages")
  async disconnectMessages(
    @common.Param() params: SchoolWhereUniqueInput,
    @common.Body() body: MessageWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      messages: {
        disconnect: body,
      },
    };
    await this.service.updateSchool({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/subjects")
  @ApiNestedQuery(SubjectFindManyArgs)
  async findSubjects(
    @common.Req() request: Request,
    @common.Param() params: SchoolWhereUniqueInput
  ): Promise<Subject[]> {
    const query = plainToClass(SubjectFindManyArgs, request.query);
    const results = await this.service.findSubjects(params.id, {
      ...query,
      select: {
        code: true,
        createdAt: true,
        id: true,
        name: true,

        school: {
          select: {
            id: true,
          },
        },

        teacher: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/subjects")
  async connectSubjects(
    @common.Param() params: SchoolWhereUniqueInput,
    @common.Body() body: SubjectWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      subjects: {
        connect: body,
      },
    };
    await this.service.updateSchool({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/subjects")
  async updateSubjects(
    @common.Param() params: SchoolWhereUniqueInput,
    @common.Body() body: SubjectWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      subjects: {
        set: body,
      },
    };
    await this.service.updateSchool({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/subjects")
  async disconnectSubjects(
    @common.Param() params: SchoolWhereUniqueInput,
    @common.Body() body: SubjectWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      subjects: {
        disconnect: body,
      },
    };
    await this.service.updateSchool({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/transactions")
  @ApiNestedQuery(TransactionFindManyArgs)
  async findTransactions(
    @common.Req() request: Request,
    @common.Param() params: SchoolWhereUniqueInput
  ): Promise<Transaction[]> {
    const query = plainToClass(TransactionFindManyArgs, request.query);
    const results = await this.service.findTransactions(params.id, {
      ...query,
      select: {
        amount: true,
        createdAt: true,

        feeStructure: {
          select: {
            id: true,
          },
        },

        gateway: true,
        gatewayTransactionId: true,
        id: true,
        paymentMethod: true,
        receiptUrl: true,

        school: {
          select: {
            id: true,
          },
        },

        status: true,
        student: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/transactions")
  async connectTransactions(
    @common.Param() params: SchoolWhereUniqueInput,
    @common.Body() body: TransactionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      transactions: {
        connect: body,
      },
    };
    await this.service.updateSchool({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/transactions")
  async updateTransactions(
    @common.Param() params: SchoolWhereUniqueInput,
    @common.Body() body: TransactionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      transactions: {
        set: body,
      },
    };
    await this.service.updateSchool({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/transactions")
  async disconnectTransactions(
    @common.Param() params: SchoolWhereUniqueInput,
    @common.Body() body: TransactionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      transactions: {
        disconnect: body,
      },
    };
    await this.service.updateSchool({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/users")
  @ApiNestedQuery(UserFindManyArgs)
  async findUsers(
    @common.Req() request: Request,
    @common.Param() params: SchoolWhereUniqueInput
  ): Promise<User[]> {
    const query = plainToClass(UserFindManyArgs, request.query);
    const results = await this.service.findUsers(params.id, {
      ...query,
      select: {
        createdAt: true,
        email: true,
        firstName: true,
        id: true,
        isActive: true,
        lastLogin: true,
        lastName: true,
        passwordHash: true,
        role: true,
        roles: true,

        school: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
        username: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/users")
  async connectUsers(
    @common.Param() params: SchoolWhereUniqueInput,
    @common.Body() body: UserWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      users: {
        connect: body,
      },
    };
    await this.service.updateSchool({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/users")
  async updateUsers(
    @common.Param() params: SchoolWhereUniqueInput,
    @common.Body() body: UserWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      users: {
        set: body,
      },
    };
    await this.service.updateSchool({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/users")
  async disconnectUsers(
    @common.Param() params: SchoolWhereUniqueInput,
    @common.Body() body: UserWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      users: {
        disconnect: body,
      },
    };
    await this.service.updateSchool({
      where: params,
      data,
      select: { id: true },
    });
  }
}
