/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { AnnouncementCreateNestedManyWithoutSchoolsInput } from "./AnnouncementCreateNestedManyWithoutSchoolsInput";
import {
  ValidateNested,
  IsOptional,
  IsString,
  MaxLength,
  IsEnum,
} from "class-validator";
import { Type } from "class-transformer";
import { AttendanceCreateNestedManyWithoutSchoolsInput } from "./AttendanceCreateNestedManyWithoutSchoolsInput";
import { ClassModelCreateNestedManyWithoutSchoolsInput } from "./ClassModelCreateNestedManyWithoutSchoolsInput";
import { IsJSONValue } from "../../validators";
import { GraphQLJSON } from "graphql-type-json";
import { InputJsonValue } from "../../types";
import { FeeStructureCreateNestedManyWithoutSchoolsInput } from "./FeeStructureCreateNestedManyWithoutSchoolsInput";
import { GradeCreateNestedManyWithoutSchoolsInput } from "./GradeCreateNestedManyWithoutSchoolsInput";
import { MessageCreateNestedManyWithoutSchoolsInput } from "./MessageCreateNestedManyWithoutSchoolsInput";
import { SubjectCreateNestedManyWithoutSchoolsInput } from "./SubjectCreateNestedManyWithoutSchoolsInput";
import { EnumSchoolSubscriptionTier } from "./EnumSchoolSubscriptionTier";
import { TransactionCreateNestedManyWithoutSchoolsInput } from "./TransactionCreateNestedManyWithoutSchoolsInput";
import { UserCreateNestedManyWithoutSchoolsInput } from "./UserCreateNestedManyWithoutSchoolsInput";

@InputType()
class SchoolCreateInput {
  @ApiProperty({
    required: false,
    type: () => AnnouncementCreateNestedManyWithoutSchoolsInput,
  })
  @ValidateNested()
  @Type(() => AnnouncementCreateNestedManyWithoutSchoolsInput)
  @IsOptional()
  @Field(() => AnnouncementCreateNestedManyWithoutSchoolsInput, {
    nullable: true,
  })
  announcements?: AnnouncementCreateNestedManyWithoutSchoolsInput;

  @ApiProperty({
    required: false,
    type: () => AttendanceCreateNestedManyWithoutSchoolsInput,
  })
  @ValidateNested()
  @Type(() => AttendanceCreateNestedManyWithoutSchoolsInput)
  @IsOptional()
  @Field(() => AttendanceCreateNestedManyWithoutSchoolsInput, {
    nullable: true,
  })
  attendances?: AttendanceCreateNestedManyWithoutSchoolsInput;

  @ApiProperty({
    required: false,
    type: () => ClassModelCreateNestedManyWithoutSchoolsInput,
  })
  @ValidateNested()
  @Type(() => ClassModelCreateNestedManyWithoutSchoolsInput)
  @IsOptional()
  @Field(() => ClassModelCreateNestedManyWithoutSchoolsInput, {
    nullable: true,
  })
  classes?: ClassModelCreateNestedManyWithoutSchoolsInput;

  @ApiProperty({
    required: false,
  })
  @IsJSONValue()
  @IsOptional()
  @Field(() => GraphQLJSON, {
    nullable: true,
  })
  configField?: InputJsonValue;

  @ApiProperty({
    required: false,
    type: () => FeeStructureCreateNestedManyWithoutSchoolsInput,
  })
  @ValidateNested()
  @Type(() => FeeStructureCreateNestedManyWithoutSchoolsInput)
  @IsOptional()
  @Field(() => FeeStructureCreateNestedManyWithoutSchoolsInput, {
    nullable: true,
  })
  feeStructures?: FeeStructureCreateNestedManyWithoutSchoolsInput;

  @ApiProperty({
    required: false,
    type: () => GradeCreateNestedManyWithoutSchoolsInput,
  })
  @ValidateNested()
  @Type(() => GradeCreateNestedManyWithoutSchoolsInput)
  @IsOptional()
  @Field(() => GradeCreateNestedManyWithoutSchoolsInput, {
    nullable: true,
  })
  grades?: GradeCreateNestedManyWithoutSchoolsInput;

  @ApiProperty({
    required: false,
    type: () => MessageCreateNestedManyWithoutSchoolsInput,
  })
  @ValidateNested()
  @Type(() => MessageCreateNestedManyWithoutSchoolsInput)
  @IsOptional()
  @Field(() => MessageCreateNestedManyWithoutSchoolsInput, {
    nullable: true,
  })
  messages?: MessageCreateNestedManyWithoutSchoolsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  subdomain?: string | null;

  @ApiProperty({
    required: false,
    type: () => SubjectCreateNestedManyWithoutSchoolsInput,
  })
  @ValidateNested()
  @Type(() => SubjectCreateNestedManyWithoutSchoolsInput)
  @IsOptional()
  @Field(() => SubjectCreateNestedManyWithoutSchoolsInput, {
    nullable: true,
  })
  subjects?: SubjectCreateNestedManyWithoutSchoolsInput;

  @ApiProperty({
    required: false,
    enum: EnumSchoolSubscriptionTier,
  })
  @IsEnum(EnumSchoolSubscriptionTier)
  @IsOptional()
  @Field(() => EnumSchoolSubscriptionTier, {
    nullable: true,
  })
  subscriptionTier?: "Option1" | null;

  @ApiProperty({
    required: false,
    type: () => TransactionCreateNestedManyWithoutSchoolsInput,
  })
  @ValidateNested()
  @Type(() => TransactionCreateNestedManyWithoutSchoolsInput)
  @IsOptional()
  @Field(() => TransactionCreateNestedManyWithoutSchoolsInput, {
    nullable: true,
  })
  transactions?: TransactionCreateNestedManyWithoutSchoolsInput;

  @ApiProperty({
    required: false,
    type: () => UserCreateNestedManyWithoutSchoolsInput,
  })
  @ValidateNested()
  @Type(() => UserCreateNestedManyWithoutSchoolsInput)
  @IsOptional()
  @Field(() => UserCreateNestedManyWithoutSchoolsInput, {
    nullable: true,
  })
  users?: UserCreateNestedManyWithoutSchoolsInput;
}

export { SchoolCreateInput as SchoolCreateInput };
