/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";

import {
  Prisma,
  School as PrismaSchool,
  Announcement as PrismaAnnouncement,
  Attendance as PrismaAttendance,
  ClassModel as PrismaClassModel,
  FeeStructure as PrismaFeeStructure,
  Grade as PrismaGrade,
  Message as PrismaMessage,
  Subject as PrismaSubject,
  Transaction as PrismaTransaction,
  User as PrismaUser,
} from "@prisma/client";

export class SchoolServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(args: Omit<Prisma.SchoolCountArgs, "select">): Promise<number> {
    return this.prisma.school.count(args);
  }

  async schools(args: Prisma.SchoolFindManyArgs): Promise<PrismaSchool[]> {
    return this.prisma.school.findMany(args);
  }
  async school(
    args: Prisma.SchoolFindUniqueArgs
  ): Promise<PrismaSchool | null> {
    return this.prisma.school.findUnique(args);
  }
  async createSchool(args: Prisma.SchoolCreateArgs): Promise<PrismaSchool> {
    return this.prisma.school.create(args);
  }
  async updateSchool(args: Prisma.SchoolUpdateArgs): Promise<PrismaSchool> {
    return this.prisma.school.update(args);
  }
  async deleteSchool(args: Prisma.SchoolDeleteArgs): Promise<PrismaSchool> {
    return this.prisma.school.delete(args);
  }

  async findAnnouncements(
    parentId: string,
    args: Prisma.AnnouncementFindManyArgs
  ): Promise<PrismaAnnouncement[]> {
    return this.prisma.school
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .announcements(args);
  }

  async findAttendances(
    parentId: string,
    args: Prisma.AttendanceFindManyArgs
  ): Promise<PrismaAttendance[]> {
    return this.prisma.school
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .attendances(args);
  }

  async findClasses(
    parentId: string,
    args: Prisma.ClassModelFindManyArgs
  ): Promise<PrismaClassModel[]> {
    return this.prisma.school
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .classes(args);
  }

  async findFeeStructures(
    parentId: string,
    args: Prisma.FeeStructureFindManyArgs
  ): Promise<PrismaFeeStructure[]> {
    return this.prisma.school
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .feeStructures(args);
  }

  async findGrades(
    parentId: string,
    args: Prisma.GradeFindManyArgs
  ): Promise<PrismaGrade[]> {
    return this.prisma.school
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .grades(args);
  }

  async findMessages(
    parentId: string,
    args: Prisma.MessageFindManyArgs
  ): Promise<PrismaMessage[]> {
    return this.prisma.school
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .messages(args);
  }

  async findSubjects(
    parentId: string,
    args: Prisma.SubjectFindManyArgs
  ): Promise<PrismaSubject[]> {
    return this.prisma.school
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .subjects(args);
  }

  async findTransactions(
    parentId: string,
    args: Prisma.TransactionFindManyArgs
  ): Promise<PrismaTransaction[]> {
    return this.prisma.school
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .transactions(args);
  }

  async findUsers(
    parentId: string,
    args: Prisma.UserFindManyArgs
  ): Promise<PrismaUser[]> {
    return this.prisma.school
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .users(args);
  }
}
