/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { School } from "./School";
import { SchoolCountArgs } from "./SchoolCountArgs";
import { SchoolFindManyArgs } from "./SchoolFindManyArgs";
import { SchoolFindUniqueArgs } from "./SchoolFindUniqueArgs";
import { CreateSchoolArgs } from "./CreateSchoolArgs";
import { UpdateSchoolArgs } from "./UpdateSchoolArgs";
import { DeleteSchoolArgs } from "./DeleteSchoolArgs";
import { AnnouncementFindManyArgs } from "../../announcement/base/AnnouncementFindManyArgs";
import { Announcement } from "../../announcement/base/Announcement";
import { AttendanceFindManyArgs } from "../../attendance/base/AttendanceFindManyArgs";
import { Attendance } from "../../attendance/base/Attendance";
import { ClassModelFindManyArgs } from "../../classModel/base/ClassModelFindManyArgs";
import { ClassModel } from "../../classModel/base/ClassModel";
import { FeeStructureFindManyArgs } from "../../feeStructure/base/FeeStructureFindManyArgs";
import { FeeStructure } from "../../feeStructure/base/FeeStructure";
import { GradeFindManyArgs } from "../../grade/base/GradeFindManyArgs";
import { Grade } from "../../grade/base/Grade";
import { MessageFindManyArgs } from "../../message/base/MessageFindManyArgs";
import { Message } from "../../message/base/Message";
import { SubjectFindManyArgs } from "../../subject/base/SubjectFindManyArgs";
import { Subject } from "../../subject/base/Subject";
import { TransactionFindManyArgs } from "../../transaction/base/TransactionFindManyArgs";
import { Transaction } from "../../transaction/base/Transaction";
import { UserFindManyArgs } from "../../user/base/UserFindManyArgs";
import { User } from "../../user/base/User";
import { SchoolService } from "../school.service";
@graphql.Resolver(() => School)
export class SchoolResolverBase {
  constructor(protected readonly service: SchoolService) {}

  async _schoolsMeta(
    @graphql.Args() args: SchoolCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [School])
  async schools(@graphql.Args() args: SchoolFindManyArgs): Promise<School[]> {
    return this.service.schools(args);
  }

  @graphql.Query(() => School, { nullable: true })
  async school(
    @graphql.Args() args: SchoolFindUniqueArgs
  ): Promise<School | null> {
    const result = await this.service.school(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => School)
  async createSchool(@graphql.Args() args: CreateSchoolArgs): Promise<School> {
    return await this.service.createSchool({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => School)
  async updateSchool(
    @graphql.Args() args: UpdateSchoolArgs
  ): Promise<School | null> {
    try {
      return await this.service.updateSchool({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => School)
  async deleteSchool(
    @graphql.Args() args: DeleteSchoolArgs
  ): Promise<School | null> {
    try {
      return await this.service.deleteSchool(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [Announcement], { name: "announcements" })
  async findAnnouncements(
    @graphql.Parent() parent: School,
    @graphql.Args() args: AnnouncementFindManyArgs
  ): Promise<Announcement[]> {
    const results = await this.service.findAnnouncements(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => [Attendance], { name: "attendances" })
  async findAttendances(
    @graphql.Parent() parent: School,
    @graphql.Args() args: AttendanceFindManyArgs
  ): Promise<Attendance[]> {
    const results = await this.service.findAttendances(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => [ClassModel], { name: "classes" })
  async findClasses(
    @graphql.Parent() parent: School,
    @graphql.Args() args: ClassModelFindManyArgs
  ): Promise<ClassModel[]> {
    const results = await this.service.findClasses(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => [FeeStructure], { name: "feeStructures" })
  async findFeeStructures(
    @graphql.Parent() parent: School,
    @graphql.Args() args: FeeStructureFindManyArgs
  ): Promise<FeeStructure[]> {
    const results = await this.service.findFeeStructures(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => [Grade], { name: "grades" })
  async findGrades(
    @graphql.Parent() parent: School,
    @graphql.Args() args: GradeFindManyArgs
  ): Promise<Grade[]> {
    const results = await this.service.findGrades(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => [Message], { name: "messages" })
  async findMessages(
    @graphql.Parent() parent: School,
    @graphql.Args() args: MessageFindManyArgs
  ): Promise<Message[]> {
    const results = await this.service.findMessages(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => [Subject], { name: "subjects" })
  async findSubjects(
    @graphql.Parent() parent: School,
    @graphql.Args() args: SubjectFindManyArgs
  ): Promise<Subject[]> {
    const results = await this.service.findSubjects(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => [Transaction], { name: "transactions" })
  async findTransactions(
    @graphql.Parent() parent: School,
    @graphql.Args() args: TransactionFindManyArgs
  ): Promise<Transaction[]> {
    const results = await this.service.findTransactions(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => [User], { name: "users" })
  async findUsers(
    @graphql.Parent() parent: School,
    @graphql.Args() args: UserFindManyArgs
  ): Promise<User[]> {
    const results = await this.service.findUsers(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }
}
