/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { ClassModelService } from "../classModel.service";
import { ClassModelCreateInput } from "./ClassModelCreateInput";
import { ClassModel } from "./ClassModel";
import { ClassModelFindManyArgs } from "./ClassModelFindManyArgs";
import { ClassModelWhereUniqueInput } from "./ClassModelWhereUniqueInput";
import { ClassModelUpdateInput } from "./ClassModelUpdateInput";
import { AttendanceFindManyArgs } from "../../attendance/base/AttendanceFindManyArgs";
import { Attendance } from "../../attendance/base/Attendance";
import { AttendanceWhereUniqueInput } from "../../attendance/base/AttendanceWhereUniqueInput";
import { StudentProfileFindManyArgs } from "../../studentProfile/base/StudentProfileFindManyArgs";
import { StudentProfile } from "../../studentProfile/base/StudentProfile";
import { StudentProfileWhereUniqueInput } from "../../studentProfile/base/StudentProfileWhereUniqueInput";

export class ClassModelControllerBase {
  constructor(protected readonly service: ClassModelService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: ClassModel })
  async createClassModel(
    @common.Body() data: ClassModelCreateInput
  ): Promise<ClassModel> {
    return await this.service.createClassModel({
      data: {
        ...data,

        school: data.school
          ? {
              connect: data.school,
            }
          : undefined,
      },
      select: {
        academicYear: true,
        capacity: true,
        classTeacher: true,
        createdAt: true,
        id: true,
        name: true,

        school: {
          select: {
            id: true,
          },
        },

        section: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [ClassModel] })
  @ApiNestedQuery(ClassModelFindManyArgs)
  async classModels(@common.Req() request: Request): Promise<ClassModel[]> {
    const args = plainToClass(ClassModelFindManyArgs, request.query);
    return this.service.classModels({
      ...args,
      select: {
        academicYear: true,
        capacity: true,
        classTeacher: true,
        createdAt: true,
        id: true,
        name: true,

        school: {
          select: {
            id: true,
          },
        },

        section: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: ClassModel })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async classModel(
    @common.Param() params: ClassModelWhereUniqueInput
  ): Promise<ClassModel | null> {
    const result = await this.service.classModel({
      where: params,
      select: {
        academicYear: true,
        capacity: true,
        classTeacher: true,
        createdAt: true,
        id: true,
        name: true,

        school: {
          select: {
            id: true,
          },
        },

        section: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: ClassModel })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateClassModel(
    @common.Param() params: ClassModelWhereUniqueInput,
    @common.Body() data: ClassModelUpdateInput
  ): Promise<ClassModel | null> {
    try {
      return await this.service.updateClassModel({
        where: params,
        data: {
          ...data,

          school: data.school
            ? {
                connect: data.school,
              }
            : undefined,
        },
        select: {
          academicYear: true,
          capacity: true,
          classTeacher: true,
          createdAt: true,
          id: true,
          name: true,

          school: {
            select: {
              id: true,
            },
          },

          section: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: ClassModel })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteClassModel(
    @common.Param() params: ClassModelWhereUniqueInput
  ): Promise<ClassModel | null> {
    try {
      return await this.service.deleteClassModel({
        where: params,
        select: {
          academicYear: true,
          capacity: true,
          classTeacher: true,
          createdAt: true,
          id: true,
          name: true,

          school: {
            select: {
              id: true,
            },
          },

          section: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/attendances")
  @ApiNestedQuery(AttendanceFindManyArgs)
  async findAttendances(
    @common.Req() request: Request,
    @common.Param() params: ClassModelWhereUniqueInput
  ): Promise<Attendance[]> {
    const query = plainToClass(AttendanceFindManyArgs, request.query);
    const results = await this.service.findAttendances(params.id, {
      ...query,
      select: {
        classField: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        date: true,
        id: true,
        markedBy: true,

        school: {
          select: {
            id: true,
          },
        },

        session: true,
        status: true,
        student: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/attendances")
  async connectAttendances(
    @common.Param() params: ClassModelWhereUniqueInput,
    @common.Body() body: AttendanceWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      attendances: {
        connect: body,
      },
    };
    await this.service.updateClassModel({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/attendances")
  async updateAttendances(
    @common.Param() params: ClassModelWhereUniqueInput,
    @common.Body() body: AttendanceWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      attendances: {
        set: body,
      },
    };
    await this.service.updateClassModel({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/attendances")
  async disconnectAttendances(
    @common.Param() params: ClassModelWhereUniqueInput,
    @common.Body() body: AttendanceWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      attendances: {
        disconnect: body,
      },
    };
    await this.service.updateClassModel({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/studentProfiles")
  @ApiNestedQuery(StudentProfileFindManyArgs)
  async findStudentProfiles(
    @common.Req() request: Request,
    @common.Param() params: ClassModelWhereUniqueInput
  ): Promise<StudentProfile[]> {
    const query = plainToClass(StudentProfileFindManyArgs, request.query);
    const results = await this.service.findStudentProfiles(params.id, {
      ...query,
      select: {
        admissionNo: true,

        classField: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        dateOfBirth: true,
        emergencyContacts: true,
        id: true,
        medicalInfo: true,
        rollNo: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/studentProfiles")
  async connectStudentProfiles(
    @common.Param() params: ClassModelWhereUniqueInput,
    @common.Body() body: StudentProfileWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      studentProfiles: {
        connect: body,
      },
    };
    await this.service.updateClassModel({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/studentProfiles")
  async updateStudentProfiles(
    @common.Param() params: ClassModelWhereUniqueInput,
    @common.Body() body: StudentProfileWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      studentProfiles: {
        set: body,
      },
    };
    await this.service.updateClassModel({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/studentProfiles")
  async disconnectStudentProfiles(
    @common.Param() params: ClassModelWhereUniqueInput,
    @common.Body() body: StudentProfileWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      studentProfiles: {
        disconnect: body,
      },
    };
    await this.service.updateClassModel({
      where: params,
      data,
      select: { id: true },
    });
  }
}
