/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  MaxLength,
  IsOptional,
  ValidateNested,
  IsInt,
  Min,
  Max,
} from "class-validator";
import { AttendanceCreateNestedManyWithoutClassModelsInput } from "./AttendanceCreateNestedManyWithoutClassModelsInput";
import { Type } from "class-transformer";
import { SchoolWhereUniqueInput } from "../../school/base/SchoolWhereUniqueInput";
import { StudentProfileCreateNestedManyWithoutClassModelsInput } from "./StudentProfileCreateNestedManyWithoutClassModelsInput";

@InputType()
class ClassModelCreateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  academicYear?: string | null;

  @ApiProperty({
    required: false,
    type: () => AttendanceCreateNestedManyWithoutClassModelsInput,
  })
  @ValidateNested()
  @Type(() => AttendanceCreateNestedManyWithoutClassModelsInput)
  @IsOptional()
  @Field(() => AttendanceCreateNestedManyWithoutClassModelsInput, {
    nullable: true,
  })
  attendances?: AttendanceCreateNestedManyWithoutClassModelsInput;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @Min(-999999999)
  @Max(999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  capacity?: number | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  classTeacher?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string | null;

  @ApiProperty({
    required: false,
    type: () => SchoolWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => SchoolWhereUniqueInput)
  @IsOptional()
  @Field(() => SchoolWhereUniqueInput, {
    nullable: true,
  })
  school?: SchoolWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  section?: string | null;

  @ApiProperty({
    required: false,
    type: () => StudentProfileCreateNestedManyWithoutClassModelsInput,
  })
  @ValidateNested()
  @Type(() => StudentProfileCreateNestedManyWithoutClassModelsInput)
  @IsOptional()
  @Field(() => StudentProfileCreateNestedManyWithoutClassModelsInput, {
    nullable: true,
  })
  studentProfiles?: StudentProfileCreateNestedManyWithoutClassModelsInput;
}

export { ClassModelCreateInput as ClassModelCreateInput };
