/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { StudentProfileService } from "../studentProfile.service";
import { StudentProfileCreateInput } from "./StudentProfileCreateInput";
import { StudentProfile } from "./StudentProfile";
import { StudentProfileFindManyArgs } from "./StudentProfileFindManyArgs";
import { StudentProfileWhereUniqueInput } from "./StudentProfileWhereUniqueInput";
import { StudentProfileUpdateInput } from "./StudentProfileUpdateInput";

export class StudentProfileControllerBase {
  constructor(protected readonly service: StudentProfileService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: StudentProfile })
  async createStudentProfile(
    @common.Body() data: StudentProfileCreateInput
  ): Promise<StudentProfile> {
    return await this.service.createStudentProfile({
      data: {
        ...data,

        classField: data.classField
          ? {
              connect: data.classField,
            }
          : undefined,

        user: data.user
          ? {
              connect: data.user,
            }
          : undefined,
      },
      select: {
        admissionNo: true,

        classField: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        dateOfBirth: true,
        emergencyContacts: true,
        id: true,
        medicalInfo: true,
        rollNo: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [StudentProfile] })
  @ApiNestedQuery(StudentProfileFindManyArgs)
  async studentProfiles(
    @common.Req() request: Request
  ): Promise<StudentProfile[]> {
    const args = plainToClass(StudentProfileFindManyArgs, request.query);
    return this.service.studentProfiles({
      ...args,
      select: {
        admissionNo: true,

        classField: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        dateOfBirth: true,
        emergencyContacts: true,
        id: true,
        medicalInfo: true,
        rollNo: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: StudentProfile })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async studentProfile(
    @common.Param() params: StudentProfileWhereUniqueInput
  ): Promise<StudentProfile | null> {
    const result = await this.service.studentProfile({
      where: params,
      select: {
        admissionNo: true,

        classField: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        dateOfBirth: true,
        emergencyContacts: true,
        id: true,
        medicalInfo: true,
        rollNo: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: StudentProfile })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateStudentProfile(
    @common.Param() params: StudentProfileWhereUniqueInput,
    @common.Body() data: StudentProfileUpdateInput
  ): Promise<StudentProfile | null> {
    try {
      return await this.service.updateStudentProfile({
        where: params,
        data: {
          ...data,

          classField: data.classField
            ? {
                connect: data.classField,
              }
            : undefined,

          user: data.user
            ? {
                connect: data.user,
              }
            : undefined,
        },
        select: {
          admissionNo: true,

          classField: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          dateOfBirth: true,
          emergencyContacts: true,
          id: true,
          medicalInfo: true,
          rollNo: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: StudentProfile })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteStudentProfile(
    @common.Param() params: StudentProfileWhereUniqueInput
  ): Promise<StudentProfile | null> {
    try {
      return await this.service.deleteStudentProfile({
        where: params,
        select: {
          admissionNo: true,

          classField: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          dateOfBirth: true,
          emergencyContacts: true,
          id: true,
          medicalInfo: true,
          rollNo: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
