/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";

import {
  IsNumber,
  Min,
  Max,
  IsOptional,
  IsEnum,
  IsInt,
  IsString,
  MaxLength,
  ValidateNested,
} from "class-validator";

import { IsJSONValue } from "../../validators";
import { GraphQLJSON } from "graphql-type-json";
import { InputJsonValue } from "../../types";
import { EnumFeeStructureCategory } from "./EnumFeeStructureCategory";
import { SchoolWhereUniqueInput } from "../../school/base/SchoolWhereUniqueInput";
import { Type } from "class-transformer";
import { TransactionCreateNestedManyWithoutFeeStructuresInput } from "./TransactionCreateNestedManyWithoutFeeStructuresInput";

@InputType()
class FeeStructureCreateInput {
  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Min(-999999999)
  @Max(999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  amount?: number | null;

  @ApiProperty({
    required: false,
  })
  @IsJSONValue()
  @IsOptional()
  @Field(() => GraphQLJSON, {
    nullable: true,
  })
  applicableClassIds?: InputJsonValue;

  @ApiProperty({
    required: false,
    enum: EnumFeeStructureCategory,
  })
  @IsEnum(EnumFeeStructureCategory)
  @IsOptional()
  @Field(() => EnumFeeStructureCategory, {
    nullable: true,
  })
  category?: "Option1" | null;

  @ApiProperty({
    required: false,
  })
  @IsJSONValue()
  @IsOptional()
  @Field(() => GraphQLJSON, {
    nullable: true,
  })
  dueDates?: InputJsonValue;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @Min(-999999999)
  @Max(999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  installmentCount?: number | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string | null;

  @ApiProperty({
    required: false,
    type: () => SchoolWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => SchoolWhereUniqueInput)
  @IsOptional()
  @Field(() => SchoolWhereUniqueInput, {
    nullable: true,
  })
  school?: SchoolWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => TransactionCreateNestedManyWithoutFeeStructuresInput,
  })
  @ValidateNested()
  @Type(() => TransactionCreateNestedManyWithoutFeeStructuresInput)
  @IsOptional()
  @Field(() => TransactionCreateNestedManyWithoutFeeStructuresInput, {
    nullable: true,
  })
  transactions?: TransactionCreateNestedManyWithoutFeeStructuresInput;
}

export { FeeStructureCreateInput as FeeStructureCreateInput };
