/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";

import {
  Prisma,
  FeeStructure as PrismaFeeStructure,
  Transaction as PrismaTransaction,
  School as PrismaSchool,
} from "@prisma/client";

export class FeeStructureServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.FeeStructureCountArgs, "select">
  ): Promise<number> {
    return this.prisma.feeStructure.count(args);
  }

  async feeStructures(
    args: Prisma.FeeStructureFindManyArgs
  ): Promise<PrismaFeeStructure[]> {
    return this.prisma.feeStructure.findMany(args);
  }
  async feeStructure(
    args: Prisma.FeeStructureFindUniqueArgs
  ): Promise<PrismaFeeStructure | null> {
    return this.prisma.feeStructure.findUnique(args);
  }
  async createFeeStructure(
    args: Prisma.FeeStructureCreateArgs
  ): Promise<PrismaFeeStructure> {
    return this.prisma.feeStructure.create(args);
  }
  async updateFeeStructure(
    args: Prisma.FeeStructureUpdateArgs
  ): Promise<PrismaFeeStructure> {
    return this.prisma.feeStructure.update(args);
  }
  async deleteFeeStructure(
    args: Prisma.FeeStructureDeleteArgs
  ): Promise<PrismaFeeStructure> {
    return this.prisma.feeStructure.delete(args);
  }

  async findTransactions(
    parentId: string,
    args: Prisma.TransactionFindManyArgs
  ): Promise<PrismaTransaction[]> {
    return this.prisma.feeStructure
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .transactions(args);
  }

  async getSchool(parentId: string): Promise<PrismaSchool | null> {
    return this.prisma.feeStructure
      .findUnique({
        where: { id: parentId },
      })
      .school();
  }
}
