/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { FeeStructureService } from "../feeStructure.service";
import { FeeStructureCreateInput } from "./FeeStructureCreateInput";
import { FeeStructure } from "./FeeStructure";
import { FeeStructureFindManyArgs } from "./FeeStructureFindManyArgs";
import { FeeStructureWhereUniqueInput } from "./FeeStructureWhereUniqueInput";
import { FeeStructureUpdateInput } from "./FeeStructureUpdateInput";
import { TransactionFindManyArgs } from "../../transaction/base/TransactionFindManyArgs";
import { Transaction } from "../../transaction/base/Transaction";
import { TransactionWhereUniqueInput } from "../../transaction/base/TransactionWhereUniqueInput";

export class FeeStructureControllerBase {
  constructor(protected readonly service: FeeStructureService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: FeeStructure })
  async createFeeStructure(
    @common.Body() data: FeeStructureCreateInput
  ): Promise<FeeStructure> {
    return await this.service.createFeeStructure({
      data: {
        ...data,

        school: data.school
          ? {
              connect: data.school,
            }
          : undefined,
      },
      select: {
        amount: true,
        applicableClassIds: true,
        category: true,
        createdAt: true,
        dueDates: true,
        id: true,
        installmentCount: true,
        name: true,

        school: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [FeeStructure] })
  @ApiNestedQuery(FeeStructureFindManyArgs)
  async feeStructures(@common.Req() request: Request): Promise<FeeStructure[]> {
    const args = plainToClass(FeeStructureFindManyArgs, request.query);
    return this.service.feeStructures({
      ...args,
      select: {
        amount: true,
        applicableClassIds: true,
        category: true,
        createdAt: true,
        dueDates: true,
        id: true,
        installmentCount: true,
        name: true,

        school: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: FeeStructure })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async feeStructure(
    @common.Param() params: FeeStructureWhereUniqueInput
  ): Promise<FeeStructure | null> {
    const result = await this.service.feeStructure({
      where: params,
      select: {
        amount: true,
        applicableClassIds: true,
        category: true,
        createdAt: true,
        dueDates: true,
        id: true,
        installmentCount: true,
        name: true,

        school: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: FeeStructure })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateFeeStructure(
    @common.Param() params: FeeStructureWhereUniqueInput,
    @common.Body() data: FeeStructureUpdateInput
  ): Promise<FeeStructure | null> {
    try {
      return await this.service.updateFeeStructure({
        where: params,
        data: {
          ...data,

          school: data.school
            ? {
                connect: data.school,
              }
            : undefined,
        },
        select: {
          amount: true,
          applicableClassIds: true,
          category: true,
          createdAt: true,
          dueDates: true,
          id: true,
          installmentCount: true,
          name: true,

          school: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: FeeStructure })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteFeeStructure(
    @common.Param() params: FeeStructureWhereUniqueInput
  ): Promise<FeeStructure | null> {
    try {
      return await this.service.deleteFeeStructure({
        where: params,
        select: {
          amount: true,
          applicableClassIds: true,
          category: true,
          createdAt: true,
          dueDates: true,
          id: true,
          installmentCount: true,
          name: true,

          school: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/transactions")
  @ApiNestedQuery(TransactionFindManyArgs)
  async findTransactions(
    @common.Req() request: Request,
    @common.Param() params: FeeStructureWhereUniqueInput
  ): Promise<Transaction[]> {
    const query = plainToClass(TransactionFindManyArgs, request.query);
    const results = await this.service.findTransactions(params.id, {
      ...query,
      select: {
        amount: true,
        createdAt: true,

        feeStructure: {
          select: {
            id: true,
          },
        },

        gateway: true,
        gatewayTransactionId: true,
        id: true,
        paymentMethod: true,
        receiptUrl: true,

        school: {
          select: {
            id: true,
          },
        },

        status: true,
        student: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/transactions")
  async connectTransactions(
    @common.Param() params: FeeStructureWhereUniqueInput,
    @common.Body() body: TransactionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      transactions: {
        connect: body,
      },
    };
    await this.service.updateFeeStructure({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/transactions")
  async updateTransactions(
    @common.Param() params: FeeStructureWhereUniqueInput,
    @common.Body() body: TransactionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      transactions: {
        set: body,
      },
    };
    await this.service.updateFeeStructure({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/transactions")
  async disconnectTransactions(
    @common.Param() params: FeeStructureWhereUniqueInput,
    @common.Body() body: TransactionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      transactions: {
        disconnect: body,
      },
    };
    await this.service.updateFeeStructure({
      where: params,
      data,
      select: { id: true },
    });
  }
}
