/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { FeeStructure } from "./FeeStructure";
import { FeeStructureCountArgs } from "./FeeStructureCountArgs";
import { FeeStructureFindManyArgs } from "./FeeStructureFindManyArgs";
import { FeeStructureFindUniqueArgs } from "./FeeStructureFindUniqueArgs";
import { CreateFeeStructureArgs } from "./CreateFeeStructureArgs";
import { UpdateFeeStructureArgs } from "./UpdateFeeStructureArgs";
import { DeleteFeeStructureArgs } from "./DeleteFeeStructureArgs";
import { TransactionFindManyArgs } from "../../transaction/base/TransactionFindManyArgs";
import { Transaction } from "../../transaction/base/Transaction";
import { School } from "../../school/base/School";
import { FeeStructureService } from "../feeStructure.service";
@graphql.Resolver(() => FeeStructure)
export class FeeStructureResolverBase {
  constructor(protected readonly service: FeeStructureService) {}

  async _feeStructuresMeta(
    @graphql.Args() args: FeeStructureCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [FeeStructure])
  async feeStructures(
    @graphql.Args() args: FeeStructureFindManyArgs
  ): Promise<FeeStructure[]> {
    return this.service.feeStructures(args);
  }

  @graphql.Query(() => FeeStructure, { nullable: true })
  async feeStructure(
    @graphql.Args() args: FeeStructureFindUniqueArgs
  ): Promise<FeeStructure | null> {
    const result = await this.service.feeStructure(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => FeeStructure)
  async createFeeStructure(
    @graphql.Args() args: CreateFeeStructureArgs
  ): Promise<FeeStructure> {
    return await this.service.createFeeStructure({
      ...args,
      data: {
        ...args.data,

        school: args.data.school
          ? {
              connect: args.data.school,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => FeeStructure)
  async updateFeeStructure(
    @graphql.Args() args: UpdateFeeStructureArgs
  ): Promise<FeeStructure | null> {
    try {
      return await this.service.updateFeeStructure({
        ...args,
        data: {
          ...args.data,

          school: args.data.school
            ? {
                connect: args.data.school,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => FeeStructure)
  async deleteFeeStructure(
    @graphql.Args() args: DeleteFeeStructureArgs
  ): Promise<FeeStructure | null> {
    try {
      return await this.service.deleteFeeStructure(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [Transaction], { name: "transactions" })
  async findTransactions(
    @graphql.Parent() parent: FeeStructure,
    @graphql.Args() args: TransactionFindManyArgs
  ): Promise<Transaction[]> {
    const results = await this.service.findTransactions(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => School, {
    nullable: true,
    name: "school",
  })
  async getSchool(
    @graphql.Parent() parent: FeeStructure
  ): Promise<School | null> {
    const result = await this.service.getSchool(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
