/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Subject } from "./Subject";
import { SubjectCountArgs } from "./SubjectCountArgs";
import { SubjectFindManyArgs } from "./SubjectFindManyArgs";
import { SubjectFindUniqueArgs } from "./SubjectFindUniqueArgs";
import { CreateSubjectArgs } from "./CreateSubjectArgs";
import { UpdateSubjectArgs } from "./UpdateSubjectArgs";
import { DeleteSubjectArgs } from "./DeleteSubjectArgs";
import { GradeFindManyArgs } from "../../grade/base/GradeFindManyArgs";
import { Grade } from "../../grade/base/Grade";
import { School } from "../../school/base/School";
import { SubjectService } from "../subject.service";
@graphql.Resolver(() => Subject)
export class SubjectResolverBase {
  constructor(protected readonly service: SubjectService) {}

  async _subjectsMeta(
    @graphql.Args() args: SubjectCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Subject])
  async subjects(
    @graphql.Args() args: SubjectFindManyArgs
  ): Promise<Subject[]> {
    return this.service.subjects(args);
  }

  @graphql.Query(() => Subject, { nullable: true })
  async subject(
    @graphql.Args() args: SubjectFindUniqueArgs
  ): Promise<Subject | null> {
    const result = await this.service.subject(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Subject)
  async createSubject(
    @graphql.Args() args: CreateSubjectArgs
  ): Promise<Subject> {
    return await this.service.createSubject({
      ...args,
      data: {
        ...args.data,

        school: args.data.school
          ? {
              connect: args.data.school,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => Subject)
  async updateSubject(
    @graphql.Args() args: UpdateSubjectArgs
  ): Promise<Subject | null> {
    try {
      return await this.service.updateSubject({
        ...args,
        data: {
          ...args.data,

          school: args.data.school
            ? {
                connect: args.data.school,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Subject)
  async deleteSubject(
    @graphql.Args() args: DeleteSubjectArgs
  ): Promise<Subject | null> {
    try {
      return await this.service.deleteSubject(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [Grade], { name: "grades" })
  async findGrades(
    @graphql.Parent() parent: Subject,
    @graphql.Args() args: GradeFindManyArgs
  ): Promise<Grade[]> {
    const results = await this.service.findGrades(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => School, {
    nullable: true,
    name: "school",
  })
  async getSchool(@graphql.Parent() parent: Subject): Promise<School | null> {
    const result = await this.service.getSchool(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
